# Generated by Django 6.0.4 on 2026-04-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('company_logo', models.URLField(blank=True)),
                ('chart_link', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('nse_profile', models.URLField(blank=True)),
                ('bse_profile', models.URLField(blank=True)),
                ('about_company', models.TextField(blank=True)),
                ('face_value', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('roce_percentage', models.FloatField(blank=True, null=True)),
                ('roe_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dim_company',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='HealthLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'dim_health_label',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, unique=True)),
                ('sector_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dim_sector',
                'ordering': ['sector_name'],
            },
        ),
        migrations.CreateModel(
            name='YearDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('month_num', models.IntegerField(blank=True, null=True)),
                ('is_ttm', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dim_year',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('report_url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
            options={
                'db_table': 'fact_documents',
            },
        ),
        migrations.CreateModel(
            name='MLScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.FloatField(null=True)),
                ('profitability_score', models.FloatField(null=True)),
                ('growth_score', models.FloatField(null=True)),
                ('leverage_score', models.FloatField(null=True)),
                ('cashflow_score', models.FloatField(null=True)),
                ('dividend_score', models.FloatField(null=True)),
                ('trend_score', models.FloatField(null=True)),
                ('health_label', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_scores', to='companies.company')),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProsCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField()),
                ('text', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='companies.company')),
            ],
            options={
                'db_table': 'fact_pros_cons',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.sector'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=60)),
                ('period_label', models.CharField(max_length=10)),
                ('value_pct', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='companies.company')),
            ],
            options={
                'db_table': 'fact_analysis',
                'unique_together': {('company', 'metric', 'period_label')},
            },
        ),
        migrations.CreateModel(
            name='ProfitAndLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.FloatField(blank=True, null=True)),
                ('expenses', models.FloatField(blank=True, null=True)),
                ('operating_profit', models.FloatField(blank=True, null=True)),
                ('opm_pct', models.FloatField(blank=True, null=True)),
                ('other_income', models.FloatField(blank=True, null=True)),
                ('interest', models.FloatField(blank=True, null=True)),
                ('depreciation', models.FloatField(blank=True, null=True)),
                ('profit_before_tax', models.FloatField(blank=True, null=True)),
                ('tax_pct', models.FloatField(blank=True, null=True)),
                ('net_profit', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('dividend_payout_pct', models.FloatField(blank=True, null=True)),
                ('net_profit_margin_pct', models.FloatField(blank=True, null=True)),
                ('expense_ratio_pct', models.FloatField(blank=True, null=True)),
                ('interest_coverage', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='companies.yeardimension')),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'ordering': ['company', 'year__sort_order'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_activity', models.FloatField(blank=True, null=True)),
                ('investing_activity', models.FloatField(blank=True, null=True)),
                ('financing_activity', models.FloatField(blank=True, null=True)),
                ('net_cash_flow', models.FloatField(blank=True, null=True)),
                ('free_cash_flow', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='companies.yeardimension')),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'ordering': ['company', 'year__sort_order'],
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_capital', models.FloatField(blank=True, null=True)),
                ('reserves', models.FloatField(blank=True, null=True)),
                ('borrowings', models.FloatField(blank=True, null=True)),
                ('other_liabilities', models.FloatField(blank=True, null=True)),
                ('total_liabilities', models.FloatField(blank=True, null=True)),
                ('fixed_assets', models.FloatField(blank=True, null=True)),
                ('cwip', models.FloatField(blank=True, null=True)),
                ('investments', models.FloatField(blank=True, null=True)),
                ('other_assets', models.FloatField(blank=True, null=True)),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('equity_ratio', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='companies.yeardimension')),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'ordering': ['company', 'year__sort_order'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
